 version: 2.1

 workflows:
  test:
    jobs:
      - test

 jobs:
   test:
     docker:
       - image: mcr.microsoft.com/dotnet/sdk:3.1
     steps:
       - checkout
       - run: dotnet test -c Debug
